### ISSUE TITLE
`Link` and `button` race condition while logging out

### ISSUE THREAD

**Issue by MuhammadSawalhy** [13-Ronin/Frontend#6]
How is this possible? `Link` and `button` both work together after a single click! Think about race conditions which is a common problem in software engineering in many fields and technologies.

_Originally posted by @MuhammadSawalhy in https://github.com/13-Ronin/Frontend/pull/5#discussion_r1491490686_

**Comment by mohamedahmed-cloud** [comment]
I just solved this issue in the following commit [this](https://github.com/13-Ronin/Frontend/pull/8/commits/274250de5598868b1679fd3fe3fb1f1022277cc0)

**Comment by MuhammadSawalhy** [comment]
Thx
